# name: Azure pipeline

# on:
#   push:
#     branches:
#     - main

# jobs:

#   tf-run:
#     name: Terraform run on Azure
#     runs-on: ubuntu-latest
#     env:
#       ARM_CLIENT_ID      : ${{ secrets.ARM_CLIENT_ID }}
#       ARM_CLIENT_SECRET  : ${{ secrets.ARM_CLIENT_SECRET }}
#       ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#       ARM_TENANT_ID      : ${{ secrets.ARM_TENANT_ID }}
 
#     steps:

#     - name: Step 01 - Terraform Setup
#       uses: hashicorp/setup-terraform@v2
#       with:
#         terraform_version: 1.6.1

#     - name: Step 02 - Terraform Version
#       run : terraform --version

#     - name: Step 03 - CheckOut GitHub Repo
#       uses: actions/checkout@v3

#     - name: Step 04 - Authenticate with Azure
#       uses: azure/login@v1
#       with:
#         creds: '{"clientId":"${{ secrets.ARM_CLIENT_ID }}","clientSecret":"${{ secrets.ARM_CLIENT_SECRET }}","subscriptionId":"${{ secrets.ARM_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.ARM_TENANT_ID }}"}'

#     - name: Step 05 - Terraform Init
#       run : terraform -chdir=./terraform/azure init -input=false

#     - name: Step 06 - Terraform Validate
#       run : terraform -chdir=./terraform/azure validate

#     - name: Step 07 - Terraform Plan
#       # run : terraform -chdir=./terraform/azure plan -input=false -out tfplan
#       run : terraform -chdir=./terraform/azure plan -input=false -destroy -out tfplan

#     - name: Step 08 - Terraform Apply
#       run : terraform -chdir=./terraform/azure apply -auto-approve -input=false tfplan

#     - name: Step 09 - Terraform Show
#       run : terraform -chdir=./terraform/azure show
